### ISSUE TITLE
Meeting agendas

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#1]

**Comment by bellecarrell** [comment]
notes:
-anaconda environment with dependencies on grid (@abenton could you point me to setup you have?)
-sort by unique users
answers:
1. subset, then all
2. you'll see

**Comment by abenton** [comment]
My environments are exported to /home/hltcoe/abenton/py2_environment.yaml and /home/hltcoe/abenton/py3_environment.yaml

You should be able to recreate these environments with:

conda env create -f py2_environment.yml
conda env create -f py3_environment.yml
