### ISSUE TITLE
select 5 brands

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#14]
pick the 5 brands to track

check related work + see what adrian says

**Comment by abenton** [comment]
I would look to the literature to see which occupations are common across Twitter.  This paper may be useful:  [http://wwbp.org/papers/jobs15acl.pdf](http://wwbp.org/papers/jobs15acl.pdf)

You can collect data for more occupations than just five, but I would focus first on defining a concrete hypothesis: "What kind of behavior do we predict will influence success (and how will we define success)?", seeing if this hypothesis holds over a few occupation types, and only then extend it to more occupations.  That being said, if it is easy to collect data for many occupations simultaneously, then go ahead.

**Comment by bellecarrell** [comment]
@abenton yeah that paper looks helpful, thanks!

The hypothesis as of now (from the question "Does tweeting about topics related to one’s desired image correlate with greater success? ") is that tweeting more about topics related to the brand will result in more success. Dirk is looking into marketing research to see if he can help refine the hypothesis, and I'll be thinking about it too.

Oh, that makes sense. for some reason I'd been thinking we'd have to know all the brands we'd want to track right away. But we can separate out past tweets to do our time series analysis and still recover user info and such.

**Comment by bellecarrell** [comment]
I think success will be being in the top quartile of comparable users (users with same brand, same follower range) wrt value of modified log function (in draft). Does that sound reasonable?

**Comment by bellecarrell** [comment]
this has kind of morphed into 5 blogger topics.. discussing now

**Comment by bellecarrell** [comment]
initial list made... here 


travel	travel			
beauty	beauty	makeup	skin	hair
gastronomy	food	drink	cooking	
politics	politics	activism		
style	fashion	style	art	
family	family values	family	religion	community
sports	sports	baseball	basketball	soccer
