### ISSUE TITLE
determine # of users needed per follower range for each brand

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#18]
wait for adrian response, then followup

**Comment by abenton** [comment]
Hard to say off the bat.  1000 per bin would be nice, but perhaps not feasible.  It also depends on how many users we find in each bin -- e.g. if higher bins only have 100 or fewer users.

**Comment by bellecarrell** [comment]
we're going with 200 initially for the sample for annotators. total to be classified for final set trained by annotated sample, tbd.
