### ISSUE TITLE
log follower percentiles, cd plot, histogram

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#47]
- [x] ensure no duplicates for any using user id instead of json string

- [x] implement np.cumsum

- [x] update log follower percentiles post duplicate fix

- [ ] update follower histogram post duplicate fix

**Comment by bellecarrell** [comment]
going to verify functionality tomorrow

**Comment by bellecarrell** [comment]
@abenton for the standard histogram, what should I make the bins? If I let it autoset it will create very non-uniform bins, like shown [here](https://stackoverflow.com/questions/33497559/display-a-histogram-with-very-non-uniform-bin-widths). To implement the solution, I need to provide bins. I think I came up with bins somewhat randomly in an earlier iteration.

**Comment by abenton** [comment]
How about every 100 users to start out, then decide how to further aggregate based on the distribution you observe.
