### ISSUE TITLE
manually submit pull_brand_data -- week 1

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#48]
- [x] tues

- [ ] wed

- [x] thurs

- [x] fri

- [x] sat

**Comment by abenton** [comment]
Set up cron job to pull user info twice per day, and past tweets once per month.  Issue can be closed once Annabelle confirms that she is receiving mail from cron and data are being properly collected.

**Comment by bellecarrell** [comment]
around 11am:
i did not receive an email
using 
time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(latest))
the latest timestamp i see is:
'2018-09-09 18:00:33'

**Comment by bellecarrell** [comment]
@abenton at noon, received an email with the following:
sh: /home/hltcoe/acarrell/PycharmProjects/twitter_brand/pull_twitter_data/pull_brand_data.sh: No such file or directory

**Comment by bellecarrell** [comment]
going to close this, open new issue for cron job
