### ISSUE TITLE
9/20-9/21 dirk meeting

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#61]
__agenda__

- everyone's status

- residual followup from last meeting, including: recommendations from Twitter via an "in" (Dirk); discussing theories with social science colleagues; control for buying followers?

**Comment by bellecarrell** [comment]
1. look at hit + discuss
2. cost -- start at $.20 each, then raise if not completed quickly enough
3. do it ourselves?
4. residual followup

**Comment by bellecarrell** [comment]
notes: 
- dirk's emnlp paper
- grey out style instead of hide
1. headers over each radio, category, etc.; put it down to 5 minutes; fine w/o master turkers
2. cost: stay under $500 is fine; is $.10 too little?; 
3. obe

**Comment by bellecarrell** [comment]
n% of users unusable --- go over by that

**Comment by bellecarrell** [comment]
screenshots vs links: iframe?

**Comment by abenton** [comment]
Some additional notes:

- Go through couple HITs in sandbox once done developing -- use this to estimate time spent
  + Probably end up paying 6-8 cents per HIT
- See if there's a way to introduce "sanity check HITs" -- easy HITs with known answers that Turkers are presented with first (low priority, but would be nice)

**Comment by bellecarrell** [comment]
going to incorporate notes into tasking and then close
