### ISSUE TITLE
bin "other" users

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#71]
Run through all user annotations and bin \emph{Other} users appropriately, or construct
        new specialization bins if we missed a popular category.

**Comment by bellecarrell** [comment]
I see this as the first task for this (and it was listed first in the document).
@abenton questions:
1. Do you see the process as
- manually bin users currently labeled as "other" into current bins
- any users who don't fit cluster and add new specializations if necessary

2. If the process above is valid, how do we reconcile our manual annotations with the fact that the others are done by paid annotators?

**Comment by abenton** [comment]
I would reconcile as follows:

- If we assign a label to a user, the user gets that label
- if not, use MACE to choose the most likely label

**Comment by bellecarrell** [comment]
started by pulling out other rows. need to collect ids from original input, as ids in results files are truncated

**Comment by bellecarrell** [comment]
labeled first 50 and started an uncertain file. 21/50 uncertain
across prestudy, first batch and second, 707 assignments to annotate. across 3 days that's 236 annotations per day. going to spread out with coding tasks to avoid decline in annotation quality

**Comment by bellecarrell** [comment]
100 labels/hour, if not a little faster. through first 265 or so. going to get through around 100 or so more tonight
