### ISSUE TITLE
tweets by specialization

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#75]
Count number of tweets per user.  Report average by specialization, follower count,
        and final follower count \% increase.  Plot tweet count time series, per user and aggregated
        by specialization.  Total number of users + tweets + time range.

**Comment by bellecarrell** [comment]
@abenton should i report averages for static as well as time series data?

**Comment by abenton** [comment]
Yes, do static first. What were you going to generate statistics for first?
--Adrian

**Comment by bellecarrell** [comment]
The tasks I have assigned myself already I was doing first. If you think
any should be prioritized for the meeting, let me know and I'll do those as
well.
(The ones I assigned are all close to finished or finished.)
