### ISSUE TITLE
Correlation matrix over specialization.

### ISSUE THREAD

**Issue by bellecarrell** [bellecarrell/twitter_brand#78]

**Comment by bellecarrell** [comment]
@abenton could you provide an example of what this is? In my head a cell corresponding to "arts" "health" would contain "arts" intersection "health" count / max("arts","health") count to get at percentage overlap between the two

**Comment by abenton** [comment]
Just want to see which specializations tend to coocur.  A matrix of pearson correlation between if a user was tagged as specialization s_i and s_j for each pair of specializations.
