### ISSUE TITLE
Speed up timeline generation code

### ISSUE THREAD

**Issue by abenton** [bellecarrell/twitter_brand#85]
Timeline generation takes too long.  Speed up by:

- parallelizing across input files with multiprocessing module
- remove file opens + closes, leave single file open
- write info + tweet timeline to single file, all users together

**Comment by bellecarrell** [comment]
@abenton if moving to all one file, will it be a compressed file? I don't
know how big a CSV can get

**Comment by abenton** [comment]
Yes, compressed, faster to write to gzipped file.

**Comment by abenton** [comment]
Am working on it now, hopefully be done soon.

**Comment by abenton** [comment]
Running timeline generation script now.  Sample usage:

    python -m collect_users.user_info_timeline_to_dataframe_par --in_dir /exp/abenton/twitter_brand_data/ --out_dir /exp/abenton/twitter_brand/promoting_users/ --num_procs 10

Expected to finish processing processing user infos  + tweets in 6 hours.

**Comment by abenton** [comment]
Tables written to:

    User information -- /exp/abenton/twitter_brand/promoting_users/info/user_info_dynamic.tsv.gz
    User tweets -- /exp/abenton/twitter_brand/promoting_users/timeline/user_tweets.noduplicates.tsv.gz

Some lines in user_tweets.noduplicates.tsv.gz may be difficult to parse.  I recommend reading with csv module and skipping errorful lines.
